metric:
  label_offset_pred:
    0: 0
    1: 1
input_dataset:
  dataset_info: dataset.yaml
postprocess:
    detection_threshold: 0.3
    formatter:
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
    src_indices:
    - 5
    - 4
    ignore_index: null
    normalized_detections: false
    resize_with_pad: false
    save_output: false
    shuffle_indices: null
    squeeze_axis: null
preprocess:
    add_flip_image: false
    backend: cv2
    crop:
    - 320
    - 320
    interpolation: null
    pad_color: 0
    resize:
    - 320
    - 320
    data_layout: NCHW
    resize_with_pad: false
    reverse_channels: false
session:
    artifacts_folder: artifacts
    extra_inputs: null
    input_data_layout: NCHW
    input_mean:
    - 0.0
    - 0.0
    - 0.0
    input_optimization: false #input scale was 1
    input_scale:
    - 0.0039215697906911373
    - 0.00392156979069113730
    - 0.0039215697906911373
    input_shape:
      images:
      - 1
      - 3
      - 320
      - 320
    model_folder: model
    model_path: model/model.onnx
    model_type: null
    num_inputs: 1
    output_shape: null
    session_name: onnxrt
    supported_machines: null
    target_device: j721e
    target_machine: pc
    runtime_options:
      debug_level: 0
      import: 'no'
      platform: J7
      priority: 0
task_type: detection
    